#version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:anchal@db:5432/Library_app"
    volumes:
      - .:/app

  db:
    image: postgres:14.16
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anchal
      POSTGRES_DB: Library_app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Library_app" ]
      interval: 5s
      retries: 5
      timeout: 3s
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
