version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anchal
      POSTGRES_DB: Library_app
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: